trigger:
- master

resources:
- repo: self

variables:
  acrName: 'myacr.azurecr.io'
  imageName: 'speedtestpy'
  tag: '$(Build.BuildId)'
  fullImageName: '$(acrName)/$(imageName):$(tag)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: '$(acrName)/$(imageName)'
        tags: |
          $(tag)

    - task: wiz@0
      displayName: Wiz Image Scan
      inputs:
        command: 'image'
        clientid: '$(WIZ_CLIENT_ID)'
        secret: '$(WIZ_CLIENT_SECRET)'
        image: '$(fullImageName)'
        policyHitsOnly: false
        fileHashesScan: true
