trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

    - task: wiz@0
      displayName: Wiz Image Scan
      inputs:
        command: 'image'
        clientid: 'yfqzsmnuxzfotn7xvi7uvii6ngdiy67gtqtfwz4mw2wfs5prlxvws'
        secret: 'ZId1sLpbB87NFiNRycoDteCRb8SNhgqsTGvhuD7RHIGScrvDj2LfwG62LSOeM3h9'
        image: '$(tag)'
        policyHitsOnly: true
        fileHashesScan: true
